import type { NextPage } from "next";
import Head from "next/head";
import NowPlaying from "../components/NowPlaying";
import Box from "@mui/material/Box";

import { ButtonBase, Container } from "@mui/material";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Spotify - MUI SSR Component</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth="sm">
        <Box
          display="flex"
          justifyContent="center"
          alignItems="center"
          minHeight="100vh"
        >
          <NowPlaying />
        </Box>
      </Container>
    </>
  );
};

export default Home;
